# Generated by Django 3.0.8 on 2020-07-15 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20200712_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='image/default.jpg', upload_to='image-items'),
        ),
    ]
